apiVersion: v1
kind: Pod
metadata: log-app
  name: dummy-log script container
  image: busybox
spec:
  volumes:
  - name: log-volume
    emptyDir: {}
containers:
  - name: dummy-log script container
    args:
    - /bin/bash
    - c
    - >
      logdir="/var/log/example"
      mkdir -p $logdir
      while true;
      do
        timestamp=$(date +"%Y-%m-%d %H:%M:%S")
        date=$(date +"%Y-%m-%d-%H-00-00")
        uuid=$(uuidgen)
        echo "$timestamp INFO [com.commerzbank.my.logger.LoggerClass] - My dummy log message $uuid"
        echo "$timestamp INFO [com.commerzbank.my.logger.LoggerClass] - My dummy log message $uuid" >> $logdir/dummy-$date.log
        sleep 5
      done      
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/example


