apiVersion: v1
kind: Deployment
metadata: log-app
  name: 
spec:
  volumes:
  - name: log-volume
    emptyDir: {}
  containers:
    - name: dummy-log script generator
      volumeMounts:
        - mountPath: /var/log/example
    - name: FileBeat container
      volumeMounts: /var/log/example
    - name: 


