apiVersion: apps/v1
kind: Deployment
metadata: 
  name: log-app-deployment
  namespace: log-app
  labels: 
    app: log-app
spec:
  selector:
    matchLabels:
      app: log-app
  replicas: 1
  template:
    metadata:
      name: log-app-temp
      labels: 
        app: log-app
    spec:
      containers:
      - name: log-housekeeper-container
      image: registry.access.redhat.com/ubi8/ubi:8.10-901.1717584420
      command: ["/bin/sh"]
      args: ["-c", "find /var/log/example -name '*.*' -mmin +60","-delete > /dev/null"]
      volumeMounts:
      - mountPath: /var/log/example
        name: log-volume
    volumes:
        - name: log-volume
          emptyDir: {}

