apiVersion: apps/v1
kind: Deployment
metadata: 
  name: log-app-deployment
  namespace: log-app
  labels: 
    app: log-app
spec:
  selector:
    matchLabels:
      app: log-app
  replicas: 1
  template:
    metadata:
      name: log-app-temp
      labels: 
        app: log-app
    spec:
      containers:
      - name: log-housekeeper-container
        image: registry.access.redhat.com/ubi8/ubi:8.10-901.1717584420
        command: /bin/sh
        - /bin/sh
        - -c
        - |
          while true;
          do
          find /path/to/the/folder -name '*.*' -mmin +59 -delete > /dev/null
          sleep 5;
          done
        volumeMounts:
        - mountPath: /var/log/example
          name: log-volume
      - name: dummy-log-script-container
        image: registry.access.redhat.com/ubi8/ubi:8.10-901.1717584420
        command:
        - /bin/sh
        - -c
        - |
          logdir="/var/log/example"
          mkdir -p $logdir;
          while true;
          do
          timestamp=$(date +"%Y-%m-%d %H:%M:%S")
          date=$(date +"%Y-%m-%d-%H-00-00")
          uuid=$(uuidgen)
          echo "$timestamp INFO [com.co.my.logger.LoggerClass] - My dummy log message $uuid"
          echo "$timestamp INFO [com.co.my.logger.LoggerClass] - My dummy log message $uuid" >> $logdir/dummy-$date.log
          sleep 5;
          done      
        volumeMounts:
        - mountPath: /var/log/example
          name: log-volume     
      volumes:
        - name: log-volume
          emptyDir: {}
      
